
server:
  port: 6381
spring:
  application:
    name: camellia-redis-proxy-hbase

#see CamelliaRedisProxyProperties
camellia-redis-proxy:
  console-port: 16379
#  password: xxxx
  netty:
    boss-thread: 1
    work-thread: 64  #由于camellia-redis-proxy-hbase使用的是同步模型，因此work-thread设置的大一些，而不是默认的cpu核数
  monitor-enable: false
  monitor-interval-seconds: 60
  command-spend-time-monitor-enable: false #是否开启请求耗时的监控，只有monitor-enable=true才有效
  slow-command-threshold-millis-time: 2000 #慢查询的阈值，单位毫秒，只有command-spend-time-monitor-enable=true才有效
  hot-key-monitor-enable: false #是否监控热key
  hot-key-monitor-config:
    check-millis: 1000 #热key的检查周期
    check-threshold: 100 #热key的阈值，检查周期内请求次数超过该阈值被判定为热key
    check-cache-max-capacity: 1000 #检查的计数器集合的size，本身是LRU的
    max-hot-key-count: 100 #每次回调的热key个数的最大值（前N个）
  big-key-monitor-enable: false #大key检测
  big-key-monitor-config:
    string-size-threshold: 2097152 #字符串类型，value大小超过多少认为是大key
    hash-size-threshold: 2000 #hash类型，集合大小超过多少认为是大key
    zset-size-threshold: 2000 #zset类型，集合大小超过多少认为是大key
    list-size-threshold: 2000 #list类型，集合大小超过多少认为是大key
    set-size-threshold: 2000 #set类型，集合大小超过多少认为是大key

#see CamelliaHBaseProperties
camellia-hbase:
  type: local
  local:
    xml:
      xml-file: hbase.xml

#see CamelliaRedisProperties
camellia-redis:
  type: local
  local:
    resource: redis://abc@127.0.0.1:6379
